### ISSUE TITLE
Weatherflow API seems to have broken the integration

### ISSUE THREAD

**Issue by robchandhok** [briis/hass-weatherflow#81] opened 2023-08-28 20:27 UTC
See also #80 I think.

Home Assistant 2023.8.4
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230802.1 - latest

I just stopped being able to read my Tempest.  When you reload, the log reports:

`2023-08-28 12:49:19.004 WARNING (MainThread) [homeassistant.config_entries] Config entry 'TheView' for weatherflow integration not ready yet: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'sea_level_pressure'; Retrying in background`

I turned on debugging and see this pattern:

```
2023-08-28 12:50:38.459 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.218 seconds (success: True)
2023-08-28 12:50:38.878 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.419 seconds (success: False)
2023-08-28 12:51:59.649 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.195 seconds (success: True)
2023-08-28 12:52:00.141 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.492 seconds (success: False)
```
My guess is that something changed in the API return values?

I am quite puzzled.  My parents instance of HA (not up to 2023.8.4) still works with their tempest.

I have tried:
- deleting and re-adding the integration
- redownloading via HACS
- making a new access token and using it
- accessing the API via their URLs and my token, and that worked

**Comment by eelcovb** [comment] 2023-08-28 20:29
I have exactly the same versions / issue:

in my log: 

2023-08-28 16:27:52.329 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.102 seconds (success: True)
2023-08-28 16:27:52.642 DEBUG (MainThread) [custom_components.weatherflow] Finished fetching weatherflow data in 0.313 seconds (success: False)
2023-08-28 16:27:52.642 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Orlando-TerraceNET' for weatherflow integration not ready yet: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'sea_level_pressure'; Retrying in background

Tried the exact same things, rebooted everything multiple times.

**Comment by jeremyhamm** [comment] 2023-08-28 21:44
My integration is also broken with WeatherFlow

**Comment by jeremyhamm** [comment] 2023-08-28 22:50
@robchandhok Any idea what version of HA your Parents are running. I reverted to an older backup (2023.8.3) and it was still broken.

**Comment by jgosnell56** [comment] 2023-08-28 23:10
I am on 2023.8.4 of HA and seeing this same error.  HA log shows:
`2023-08-28 16:42:50.552 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Stratford' for weatherflow integration not ready yet: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'sea_level_pressure'; Retrying in background`

API from my weather station still reports sea_level_pressure so not quite sure why we are suddenly seeing this error.  Excerpt from the API webpage of my weather station:
`{
    "elevation": 189.06375122070312,
    "is_public": true,
    "latitude": 34.70208,
    "longitude": -86.43422,
    "obs": [
        {
            "air_density": 1.15988,
            "air_temperature": 23.8,
            "barometric_pressure": 988.7,
            "brightness": 5308,
            "delta_t": 0.5,
            "dew_point": 23.1,
            "feels_like": 23.8,
            "heat_index": 23.8,
            "lightning_strike_count": 1,
            "lightning_strike_count_last_1hr": 178,
            "lightning_strike_count_last_3hr": 223,
            "lightning_strike_last_distance": 10,
            "lightning_strike_last_epoch": 1693264013,
            "precip": 0.807931,
            "precip_accum_last_1hr": 14.031167,
            "precip_accum_local_day": 19.700306,
            "precip_accum_local_day_final": 20.045038,
            "precip_accum_local_yesterday": 0,
            "precip_accum_local_yesterday_final": 0,
            "precip_analysis_type_yesterday": 0,
            "precip_minutes_local_day": 90,
            "precip_minutes_local_yesterday": 0,
            "precip_minutes_local_yesterday_final": 0,
            "pressure_trend": "rising",
            "relative_humidity": 96,
            "sea_level_pressure": 1011.4,
            "solar_radiation": 44,
            "station_pressure": 988.7,
            "timestamp": 1693264013,
            "uv": 0.47,
            "wet_bulb_globe_temperature": 23.7,
            "wet_bulb_temperature": 23.3,
            "wind_avg": 0.2,
            "wind_chill": 23.8,
            "wind_direction": 332,
            "wind_gust": 0.7,
            "wind_lull": 0
        }`

**Comment by jeremyhamm** [comment] 2023-08-28 23:18
@jgosnell56 Not sure if it matters to you but you may want to hide your exact location.

**Comment by ragd011** [comment] 2023-08-29 00:50
I can confirm same issue started earlier today.  As luck would have it, we lost power at 3:40 ET and when it came back, this integration is no longer working.  Completely updated system.

Logger: homeassistant.config_entries
Source: config_entries.py:1290
First occurred: 8:39:58 PM (1 occurrences)
Last logged: 8:39:58 PM

Config entry 'The House' for weatherflow integration not ready yet: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'sea_level_pressure'; Retrying in background

**Comment by gitBrave-hub** [comment] 2023-08-29 02:09
it is broken for me too, as described above by [robchandhok](https://github.com/robchandhok)

**Comment by idaband** [comment] 2023-08-29 02:18
well time to dig into this code....uggg fun times LOL.  I already commented out some stuff...with no luck.

**Comment by idaband** [comment] 2023-08-29 02:29
> well time to dig into this code....uggg fun times LOL. I already commented out some stuff...with no luck.

so looking at the straight up forcast api data that comes back... i don't see an issue with that json.... which means...something is getting messed up as its reads the data back is my guess, which could be the python library maybe?

```
  "current_conditions": {
    "air_density": 1.2,
    "air_temperature": 13,
    "brightness": 0,
    "conditions": "Clear",
    "delta_t": 1,
    "dew_point": 12,
    "feels_like": 13,
    "icon": "clear-night",
    "is_precip_local_day_rain_check": true,
    "is_precip_local_yesterday_rain_check": true,
    "lightning_strike_count_last_1hr": 0,
    "lightning_strike_count_last_3hr": 0,
    "lightning_strike_last_distance": 41,
    "lightning_strike_last_distance_msg": "39 - 43 km",
    "lightning_strike_last_epoch": 1692936462,
    "precip_accum_local_day": 0,
    "precip_accum_local_yesterday": 0,
    "precip_minutes_local_day": 0,
    "precip_minutes_local_yesterday": 0,
    "pressure_trend": "rising",
    "relative_humidity": 93,
    "sea_level_pressure": 1016.6,
    "solar_radiation": 0,
    "station_pressure": 983,
    "time": 1693275901,
    "uv": 0,
    "wet_bulb_globe_temperature": 16,
    "wet_bulb_temperature": 12,
    "wind_avg": 0,
    "wind_direction": 0,
    "wind_direction_cardinal": "N",
    "wind_gust": 0
  },
```

**Comment by robchandhok** [comment] 2023-08-29 02:30
> @robchandhok Any idea what version of HA your Parents are running. I reverted to an older backup (2023.8.3) and it was still broken.

2023.8.3 

I am now convinced it's a bug in the config/init flow. So restart breaks it. Running instances are fine. Can't see it though.

**Comment by robchandhok** [comment] 2023-08-29 03:29
Annnnnndddd….. it’s back working. There still might be an opportunity to catch this at init (defensive programming) but I don’t hav3 an example to test against.  Hopefully working for others.

**Comment by ZeddicPrime** [comment] 2023-08-29 03:35
Just reloaded the plugin and it's still broken for me.

**Comment by robchandhok** [comment] 2023-08-29 04:17
Hmmm. Race condition?

**Comment by Yomegaman** [comment] 2023-08-29 05:19
My Weatherflow died today too.  I've tried deleting & reinstalling (HA Supervisor) but get these error lines;

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<WeatherFlowMqtt._update_forecast() done, defined at /usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/weatherflow_mqtt.py:755> exception=KeyError('sea_level_pressure')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 760, in _update_forecast
    if any(forecast := await self.forecast.update_forecast()):
  File "/usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/forecast.py", line 187, in update_forecast
    row["sea_level_pressure"]
KeyError: 'sea_level_pressure'

Then it sets up all my sensors with lines like this;
INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Status

Finally giving these errors;
Traceback (most recent call last):
  File "/usr/local/bin/weatherflow2mqtt", line 33, in <module>
    sys.exit(load_entry_point('weatherflow2mqtt==3.1.6', 'console_scripts', 'weatherflow2mqtt')())
  File "/usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/__main__.py", line 10, in main
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 859, in main
  File "/usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 232, in run_time_based_updates
  File "/usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 760, in _update_forecast
  File "/usr/local/lib/python3.10/site-packages/weatherflow2mqtt-3.1.6-py3.10.egg/weatherflow2mqtt/forecast.py", line 187, in update_forecast
KeyError: 'sea_level_pressure'

This has worked great for about a year - until today.

PLEASE HELP

**Comment by idaband** [comment] 2023-08-29 13:33
I haven't checked weatherflow community forum yet either... They might have info of changes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robchandhok** [comment] 2023-08-29 15:30
Agree with @UpDryTwist .  It's starting to look like the forecast API call is the culprit, it would be nice to still succeed with the station data in the face of that error (regardless of this specific error many of us are experiencing). I'm not a good enough python programmer to make that change tho. Just needs a wrap in an error catch.

**Comment by JtwoA** [comment] 2023-08-29 17:02
@briis - any feedback?

**Comment by briis** [comment] 2023-08-29 18:04
I have been away for a long time, so I did not monitor this for a while. I will have a look at it ASAP.

**Comment by id628** [comment] 2023-08-29 18:04
FYI, this might help. The other Home Assistant integration is having the same issue:
https://github.com/briis/hass-weatherflow2mqtt/issues/234

A stated workaround there is:

> Until there is a fix, a workaround is to remove STATION_ID and STATION_TOKEN from the config page for the weatherflow2mqtt add-on (this prevents the add-on from trying to get the forecast)

**Comment by eelcovb** [comment] 2023-08-29 19:03
Haven't looked into it thoroughly, but my 2 cents:

Looking at a piece of forecast code, I noticed 'weather_daily' and 'weather_hourly' are used as keys:

`_WEATHER_DAILY = "weather_daily"
_WEATHER_HOURLY = "weather_hourly"

_LOGGER = logging.getLogger(__name__)

WEATHER_TYPES: tuple[WeatherEntityDescription, ...] = (
    WeatherEntityDescription(
        key=_WEATHER_DAILY,
        name="Day based Forecast",
    ),
    WeatherEntityDescription(
        key=_WEATHER_HOURLY,
        name="Hourly based Forecast",
    ),
)`

However, on checking the API response, the forecast keys used seem to be 'daily' and 'hourly' (https://apidocs.tempestwx.com/reference/get_better-forecast). Again, only took a quick look, will try to look into it and test hopefully later today. We have a hurricane coming up, and it'd be great to get everything recorded in HA.

Cheers

**Comment by eelcovb** [comment] 2023-08-29 20:34
> > We have a hurricane coming up, and it'd be great to get everything recorded in HA.
> > @eelcovb
> > Where are you in the path?  Lowcountry of SC here.

Orlando, FL no direct exposure, but probably some tornado's. Stay safe!

**Comment by eelcovb** [comment] 2023-08-29 22:04
> Haven't looked into it thoroughly, but my 2 cents:
> 
> Looking at a piece of forecast code, I noticed 'weather_daily' and 'weather_hourly' are used as keys:
> 
> `_WEATHER_DAILY = "weather_daily" _WEATHER_HOURLY = "weather_hourly"
> 
> _LOGGER = logging.getLogger(**name**)
> 
> WEATHER_TYPES: tuple[WeatherEntityDescription, ...] = ( WeatherEntityDescription( key=_WEATHER_DAILY, name="Day based Forecast", ), WeatherEntityDescription( key=_WEATHER_HOURLY, name="Hourly based Forecast", ), )`
> 
> However, on checking the API response, the forecast keys used seem to be 'daily' and 'hourly' (https://apidocs.tempestwx.com/reference/get_better-forecast). Again, only took a quick look, will try to look into it and test hopefully later today. We have a hurricane coming up, and it'd be great to get everything recorded in HA.
> 
> Cheers

Checked it, not the issue.

**Comment by ldeffenb** [comment] 2023-08-29 22:27
East coast of Florida and my HA-integrated Tempest has also gone offline.  Talk about (bad) timing!

**Comment by UpDryTwist** [comment] 2023-08-29 22:56
OK, thought I wouldn't have time until this weekend, but it was bugging me (and it's driving me nuts looking at my dashboard with errors on it!), so I pulled it up in the debugger.  @briis if you didn't already figure this out, the problem is that the hourly forecast no longer includes sea_level_pressure (I wonder if there was just a firmware push?).  I'll confirm a fix and put up a pull request this evening.

For others on this thread, after I confirm, I'll let you know how you might patch until Bjarne has a chance to cut a release.

**Comment by idaband** [comment] 2023-08-29 23:54
So I tried commenting out the code for that value.  Does the python not reload when HA starts?    Which lines ect did u change... Or I could look at the pr lol

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by UpDryTwist** [comment] 2023-08-30 00:12
OK, @briis , the PR is there.  Thanks, BTW, for this fantastic implementation!  You can see how freaked out we all get when it's not working!

**Comment by idaband** [comment] 2023-08-30 02:31
I can confirm the change works.  I was able to make the change inside HA.  I'm using the OS version.

**Comment by eelcovb** [comment] 2023-08-30 13:29
> 



> OK, @briis , the PR is there. Thanks, BTW, for this fantastic implementation! You can see how freaked out we all get when it's not working!
> 
> [briis/pyweatherflowrest#3](https://github.com/briis/pyweatherflowrest/pull/3)

Works perfectly! thanks

**Comment by briis** [comment] 2023-08-30 14:04
I have now release 1.0.10 of `pyweatherflowrest` which contains the PR done by @UpDryTwist .
If everything goes well I will integrate this in a new release of this Integration later today.

**Comment by idaband** [comment] 2023-08-30 14:27
> I have now release 1.0.10 of `pyweatherflowrest` which contains the PR done by @UpDryTwist . If everything goes well I will integrate this in a new release of this Integration later today.

How does HA pick up there was a depedancy change?  Does the HACs also have to update in order to make HA pull an update with updated depedancy?

**Comment by PYehl73** [comment] 2023-08-30 14:55
Mine doesn't have an api.py file to replace?    my files are in folder just called weatherflowrest - not pyweatherflowrest?

**Comment by briis** [comment] 2023-08-30 15:03
Once I publish a new release HACS will catch that automatically.
If you can't wait for HACS to find, you can go to HACS, click the Integration and then on that page, click the 3 Dots in the Upper right Corner, and then *Update Information*. This will check immediatly.

I will release it now, with only the fix for this Issue, and then start looking at the other open Issues.

**Comment by janick** [comment] 2023-08-30 15:19
I just upgraded to 1.015 via HACS and the same error is still there.

**Comment by eelcovb** [comment] 2023-08-30 15:20
Same here. I had it running with the manual fix. That was overridden by the update and now it's broken again.

**Comment by chheiss** [comment] 2023-08-30 15:37
Same here, not working.

**Comment by UpDryTwist** [comment] 2023-08-30 15:43
> Mine doesn't have an api.py file to replace? my files are in folder just called weatherflowrest - not pyweatherflowrest?

@PYehl73, you need to find where the Python package pyweatherflowrest is installed in your system (it's a package install, not the custom component itself, which just uses this package), and that's where you'll find api.py, if you're trying to patch right away.  Waiting for the fixed overall version to be released will be your best bet if that sentence doesn't make sense to you or you're not comfortable patching Python packages.

**Comment by jeremyhamm** [comment] 2023-08-30 15:56
Updated the integration to 1.0.15 and it's still broken.

**Comment by Colorado4Wheeler** [comment] 2023-08-30 16:02
Same here, 1.0.15 did not fix the issue.

![image](https://github.com/briis/hass-weatherflow/assets/20329385/9b46adac-fc2e-497f-b574-6d906e99e311)

**Comment by robchandhok** [comment] 2023-08-30 16:09
Also remember the original issue is intermittent. For example, mine is working again and I haven't installed the new version. So there may also be something timing related between asynch calls?

**Comment by Colorado4Wheeler** [comment] 2023-08-30 16:14
@robchandhok that's interesting, I haven't had it come up once since it went down, according to my history I can see that once it became unavailable it never returned.

**Comment by ldeffenb** [comment] 2023-08-30 16:43
Mine went out at 10:07am Eastern yesterday morning, was back from 3:05pm to 5:36pm, then down until 5:19 this morning and it's been up and working since.   

I'm wondering if they have a round-robin DNS and only some of the servers have the issue and other servers are still working as expected?

**Comment by Colorado4Wheeler** [comment] 2023-08-30 16:51
Perhaps.  This did force me to create a "Smart Weather" template where it can use whichever of my weather services are available in order of my preference so I always have a "master" weather device - because I have so much riding on the values from Weatherflow and they all broke, now it can fall back to OpenWeatherMap, Accuweather or NWS.  I never needed it before but now I'm redefining everything that leaned on WeatherFlow to use the template system so there is never any down time.

But, as of now, and after several reboots and reloads and integration restarts - no WeatherFlow.

**Comment by chheiss** [comment] 2023-08-30 17:58
I have two stations, the primary is working, the secondary is out since yesterday.

**Comment by chheiss** [comment] 2023-08-30 17:59
I have two stations, the primary is working, the secondary is out since yesterday. V 15 did not makeit better.

**Comment by robchandhok** [comment] 2023-08-30 18:01
Weatherflow appear to have at least 4 round robin servers for the api.

**Comment by briis** [comment] 2023-08-30 18:59
I simply can't reproduce your issues here. I had a test instance running now for 8 hours - 1 time it couldn't fetch the data, but it worked on the next scheduled call.

Please give me some more logs from Home Assistant so that I can see where this is failing.

**Comment by chheiss** [comment] 2023-08-30 19:04
Strange. Without doing anything, I am currently getting readings for both stations. V 15

**Comment by UpDryTwist** [comment] 2023-08-30 19:04
Folks -- check your Home Assistant logs.  If you have the updated version (fully updated), and you have at least level WARNING set, you should be getting a warning in your logs.  If not, check around on your system to ensure there's not something funky that's prevented you from getting the updated pyweatherflowrest -- you might be running with the old package for some reason .  (Full disclosure, I haven't had time to run the update yet, so I can't check on my install.)

**Comment by Colorado4Wheeler** [comment] 2023-08-30 19:13
Mine also started working about 30 minutes ago without any manipulation, perhaps there was just a delay in the API propagating or something.

**Comment by janick** [comment] 2023-08-30 19:18
Still not working for me. I reloaded the integration and it still complains about the sea_level_pressure key

'''
This error originated from a custom integration.

Logger: pyweatherflowrest.api
Source: custom_components/weatherflow/__init__.py:121
Integration: WeatherFlow Weather (documentation, issues)
First occurred: 8:16:03 AM (108 occurrences)
Last logged: 12:15:17 PM

{'air_temperature': 16.0, 'conditions': 'Partly Cloudy', 'feels_like': 16.0, 'icon': 'partly-cloudy-day', 'local_day': 30, 'local_hour': 9, 'precip': 0, 'precip_icon': 'chance-rain', 'precip_probability': 0, 'precip_type': 'rain', 'relative_humidity': 78, 'time': 1693411200, 'wind_avg': 4.0, 'wind_direction': 210, 'wind_direction_cardinal': 'SSW', 'wind_gust': 4.0}
The key sea_level_pressure is missing from the following array (DEBUG logging only), causing an error. It is likely that the Weatherflow API has changed unexpectedly. pyweatherflowrest on Github.
{'air_temperature': 17.0, 'conditions': 'Partly Cloudy', 'feels_like': 17.0, 'icon': 'partly-cloudy-day', 'local_day': 30, 'local_hour': 10, 'precip': 0, 'precip_icon': 'chance-rain', 'precip_probability': 0, 'precip_type': 'storm', 'relative_humidity': 75, 'time': 1693414800, 'wind_avg': 3.0, 'wind_direction': 210, 'wind_direction_cardinal': 'SSW', 'wind_gust': 4.0}
You can set the value IGNORE_FETCH_ERRORS in pyweatherflowrest/api.py to ignore this error.
{'air_temperature': 24.0, 'conditions': 'Partly Cloudy', 'feels_like': 24.0, 'icon': 'partly-cloudy-day', 'local_day': 30, 'local_hour': 13, 'precip': 0, 'precip_icon': 'chance-rain', 'precip_probability': 0, 'precip_type': 'rain', 'relative_humidity': 49, 'time': 1693425600, 'wind_avg': 3.0, 'wind_direction': 240, 'wind_direction_cardinal': 'WSW', 'wind_gust': 4.0}
'''

**Comment by Colorado4Wheeler** [comment] 2023-08-30 19:24
I also get the sea level pressure key issue but the rest still works... until I reloaded.  I reloaded the integration to check what my exact message was on the sea level as I had already cleared my logs in system (and was too lazy to search the big log) and Weatherflow fails again.  It does seem hit-and-miss.   I'll try to do more in-depth logging but so far I'm getting about the same as @janick

**Comment by dennyChandler** [comment] 2023-08-30 19:29
Failing as well - If I can assist any further please let me know.

```
Logger: pyweatherflowrest.api
Source: custom_components/weatherflow/__init__.py:121
Integration: WeatherFlow Weather (documentation, issues)
First occurred: 2:10:28 PM (45 occurrences)
Last logged: 2:27:21 PM

The key sea_level_pressure is missing from the following array (DEBUG logging only), causing an error. It is likely that the Weatherflow API has changed unexpectedly. pyweatherflowrest on Github.
{'air_temperature': 28.0, 'conditions': 'Clear', 'feels_like': 28.0, 'icon': 'clear-day', 'local_day': 30, 'local_hour': 15, 'precip': 0, 'precip_icon': 'chance-rain', 'precip_probability': 0, 'precip_type': 'rain', 'relative_humidity': 44, 'time': 1693425600, 'wind_avg': 4.0, 'wind_direction': 60, 'wind_direction_cardinal': 'ENE', 'wind_gust': 6.0}
You can set the value IGNORE_FETCH_ERRORS in pyweatherflowrest/api.py to ignore this error.
```

**Comment by ldeffenb** [comment] 2023-08-30 19:42
> You can set the value IGNORE_FETCH_ERRORS in pyweatherflowrest/api.py to ignore this error.

Well, apparently your installation has the "IGNORE_FETCH_ERRORS" set to false, so it is failing.   I'm guessing that the released fix has this set to false as well, but it would apparently need to be set to true to actually ignore the fact that the sea_level_pressure isn't there?

**Comment by UpDryTwist** [comment] 2023-08-30 19:49
@ldeffenb - on the nose.  I left the PR set to False so that it wouldn't silently fail to get data, with no visibility . . . with a "to do" to find a way to properly configure it from the application to "true".  Maybe the right thing to do is to set it to True in the short term, until a way is there to configure it from the client . . .

**Comment by ldeffenb** [comment] 2023-08-30 19:59
At least the logs will still have the missing field(s) logged, if I read the fix source code correctly.

**Comment by robchandhok** [comment] 2023-08-30 20:44
Again my apologies for not really being a python guy, but if I could suggest (a) package a release with IGNORE_FETCH_ERRORS set to true by default, and (b) when debugging is on, log the IP address of the server (if that's possible).

I pointed the Weatherflow support folks at this ticket as well, as the intermittent behavior points to a disparity between the load balanced instances of the server.

**Comment by UpDryTwist** [comment] 2023-08-30 20:47
@ldeffenb - yes, the logging will have the offender (first one found) and (if DEBUG enabled) the overall array returned.  @robchandhok - good idea, and really my fault for having left it as False (I was erring on the side of no silent failures, but should have erred on the side of make it work).  I'll try to get to it tonight with a PR for @briis to see tomorrow.  In the meantime, folks can use the same patching instructions from my note above, which should work as-is still (**WARNING**, that's from theory, not because I tried it against the latest release!).

**Comment by UpDryTwist** [comment] 2023-08-30 22:12
@robchandhok - did the Weatherflow folks happen to mention the type of load balancing they're doing?  If they're doing DNS round-robin, then it'll be useful to get the IP address returned by DNS for any given user.  But if they have a bunch of servers behind a load balancer . . . then the IP of the actual server will be opaque to us.  And I'm loathe to add in a bunch of extra code to fetch the IP if it won't be meaningful . . .

**Comment by psmith3** [comment] 2023-08-30 22:34
I am having the same issue. Where is the pyweatherflowrest/api.py file located to edit?

**Comment by robchandhok** [comment] 2023-08-30 22:36
> @robchandhok - did the Weatherflow folks happen to mention the type of load balancing they're doing?  If they're doing DNS round-robin, then it'll be useful to get the IP address returned by DNS for any given user.  But if they have a bunch of servers behind a load balancer . . . then the IP of the actual server will be opaque to us.  And I'm loathe to add in a bunch of extra code to fetch the IP if it won't be meaningful . . .

@UpDryTwist They haven't replied yet, but you are correct it's behind ELB on AWS.  Not worth the time, I agree.  Best to just enable the robust handling of missing keys.

**Comment by rwolfe5420** [comment] 2023-08-31 01:44
Mine is also broken with the same sea level error. Not sure how to resolve the issue. So I have disabled for the time being. 

Logger: pyweatherflowrest.api
Source: custom_components/weatherflow/__init__.py:121 
Integration: WeatherFlow Weather ([documentation](https://github.com/briis/hass-weatherflow), [issues](https://github.com/briis/hass-weatherflow/issues)) 
First occurred: 9:39:37 pm (3 occurrences) 
Last logged: 9:39:37 pm

The key sea_level_pressure is missing from the following array (DEBUG logging only), causing an error. It is likely that the Weatherflow API has changed unexpectedly. pyweatherflowrest on Github.
{'air_temperature': 13.0, 'conditions': 'Clear', 'feels_like': 13.0, 'icon': 'clear-night', 'local_day': 30, 'local_hour': 22, 'precip': 0, 'precip_icon': 'chance-rain', 'precip_probability': 0, 'precip_type': 'rain', 'relative_humidity': 79, 'time': 1693447200, 'wind_avg': 3.0, 'wind_direction': 30, 'wind_direction_cardinal': 'NNE', 'wind_gust': 4.0}
You can set the value IGNORE_FETCH_ERRORS in pyweatherflowrest/api.py to ignore this error.

**Comment by yegorh** [comment] 2023-08-31 02:26
Hey guys, I updated to .15 this morning, but it didn’t fix the issue. However, I just checked and it’s working fine now.

**Comment by JtwoA** [comment] 2023-08-31 03:19
I updated and neither of my two stations was working.  Now one is/one isn't.

<img width="738" alt="image" src="https://github.com/briis/hass-weatherflow/assets/12992040/3508aaec-2001-467b-9a7d-0487f19c2d24">

**Comment by janick** [comment] 2023-08-31 03:52
What is the easiest way to break out of the shell container and edit HA files/update files directly?

<img width="600" alt="Screenshot 2023-08-30 at 20 50 59" src="https://github.com/briis/hass-weatherflow/assets/363379/0611a2d9-5471-44e7-a2c7-bb642fbdcc1a">

**Comment by briis** [comment] 2023-08-31 04:14
I have now done some more testing - and as many of you noticed, it is the Sea Level Pressure for the Hourly Forecast that is causing the problems.
I tried different Station ID's and with some of them (mine f.ex.) I get a value for sea level pressure, but for others I don't. I am not sure why, I have to get in touch with the WeatherFlow team to understand that.
In the meantime, we could work around this by setting a 0 value for sea level pressure if it does not exist?

**Comment by janick** [comment] 2023-08-31 04:21
How would HA react to a NAN value?

**Comment by UpDryTwist** [comment] 2023-08-31 04:36
Just to summarize for everyone the situation:

1. Weatherflow is having some trouble with their API.  We are speculating that they have multiple servers behind a load balancer, and that only some of the servers are poisoned.  So you will see inconsistent results depending on which server gets handed to you by the load balancer.  For the poisoned servers, neither "sea_level_pressure" nor "uv" is returned for the hourly forecasts, which breaks the Home Assistant integration.
2. Yesterday, I put in a patch that allowed the code to ignore errors (currently, only in the hourly forecasts; it could easily be extended to all the data reads).  HOWEVER, I defaulted the condition to NOT ignore the errors, with a "todo" to add some way to set it to ignore (other than by editing the file).  I did this on the misguided principle that errors shouldn't be silently ignored (e.g., for people using the component to record data, so they wouldn't have bad data recorded without a signal).  Of course, this was a mistake, as most folks would rather it just collected bad data and worked otherwise ;).
3. @briis cut a release with my PR this morning.  But of course, it was set to NOT ignore the errors, so it didn't fix things for people
4. I just submitted a PR that changes the default.  So by default it will now ignore errors in the hourly data.
5. When briis gets a chance to accept the PR and cut 1.0.16, that should start working consistently for everyone.

**Comment by briis** [comment] 2023-08-31 04:43
Thank you @UpDryTwist for this summary.

I am right now working on making it possible to toggle the IGNORE_FETCH_ERRORS from the Config Menu in the Integration. But the default will now be changed to True instead of False, so that you should get data, no matter if a single item is not present. Hopefully this can be released later today (It is early morning here in Denmark)

**Comment by briis** [comment] 2023-08-31 05:31
1.0.16 is now published, which hopefully fixes this for everybody.
I will get in touch with the WeatherFlow team to see if they can give an explanation to why some stations do not have the Sea Level Pressure in the Forecast.

I will keep this open for a while until I am sure this now works for all.

**Comment by psmith3** [comment] 2023-08-31 06:18
> 1.0.16 is now published, which hopefully fixes this for everybody. I will get in touch with the WeatherFlow team to see if they can give an explanation to why some stations do not have the Sea Level Pressure in the Forecast.
> 
> I will keep this open for a while until I am sure this now works for all.

Fixed. Thanks for this!

**Comment by deadrubberboy** [comment] 2023-08-31 10:50
> > > We have a hurricane coming up, and it'd be great to get everything recorded in HA.
> > > @eelcovb
> > > Where are you in the path?  Lowcountry of SC here.
> 
> Orlando, FL no direct exposure, but probably some tornado's. Stay safe!

Orlando here too!  Also my Tempest having same issue as others.

**Comment by robchandhok** [comment] 2023-08-31 11:29
> 1.0.16 is now published, which hopefully fixes this for everybody.
> 
> I will get in touch with the WeatherFlow team to see if they can give an explanation to why some stations do not have the Sea Level Pressure in the Forecast.
> 
> 
> 
> I will keep this open for a while until I am sure this now works for all.

Confirmed fixed for me, thank you @briis !

**Comment by JtwoA** [comment] 2023-08-31 12:19
HUZZAH!  Both units reporting in successfully - many thanks for hitting this hard, @briis - much appreciated!

**Comment by rwolfe5420** [comment] 2023-08-31 12:37
Thank You for this, mine is working as well this morning. 
    	Get Outlook for iOS
    
  

 From: Bjarne Riis ***@***.***>Sent: Thursday, August 31, 2023 1:31 AMTo: briis/hass-weatherflow ***@***.***>Cc: rwolfe5420 ***@***.***>; Comment ***@***.***>Subject: Re: [briis/hass-weatherflow] Weatherflow API seems to have broken the integration (Issue #81) 
1.0.16 is now published, which hopefully fixes this for everybody.
I will get in touch with the WeatherFlow team to see if they can give an explanation to why some stations do not have the Sea Level Pressure in the Forecast.
I will keep this open for a while until I am sure this now works for all.

**Comment by jeremyhamm** [comment] 2023-08-31 13:22
1.0.16 resolved the issue for me. Thanks for everyones hard work in fixing this.

**Comment by dennyChandler** [comment] 2023-08-31 15:48
Confirmed working here as well, thank you all for your efforts in fixing this!

**Comment by chheiss** [comment] 2023-08-31 15:56
Confirmed as working, thanks for all the effort!

**Comment by robchandhok** [comment] 2023-08-31 17:15
> I updated all my files - getting some data but many entities are showing not available?  Weather Station not giving air temp anymore??  lol  
> 

Did you update to the .16 release or patch by hand? I'm getting air temp just fine on the actual release.

**Comment by PYehl73** [comment] 2023-08-31 20:13
I updated the files manually.    What steps do I need to do for actual release? (sorry newbie to HA)

> > I updated all my files - getting some data but many entities are showing not available?  Weather Station not giving air temp anymore??  lol
> 
> Did you update to the .16 release or patch by hand? I'm getting air temp just fine on the actual release.

**Comment by Yomegaman** [comment] 2023-09-01 03:49
Your fixes have everything working perfectly for me again. (Supervisor version)

Thank you ALL so much!

**Comment by briis** [comment] 2023-09-01 05:24
I will close this now as the particular issue has been solved.
If anyone still have issues please create a new issue with data from the logs.

**Closed by briis** 2023-09-01 05:24 UTC
